[package]
name = "berori"
version = "0.1.0"
authors = ["Robert Günzler <r@gnzler.io>"]
edition = "2018"

[dependencies]
wayland-client = "0.21.10"
wayland-protocols = { version = "0.21.10", features = ["client", "unstable_protocols"] }
